#server:
#  port: 8089
##-----core------------------
#
#
#
#
#  jwt:
#    secret: asdasdasdaxavxasdadadasdsasdasdasdadsadadsasdadadsadsasd
#
#  security:
#    oauth2:
#      client:
#        registration:
#          naver:
#            client-name: naver
#            client-id: ${NAVER_CLIENT_ID}
#            client-secret: ${NAVER_CLIENT_SECRET}
#            redirect-uri: http://localhost:8089/login/oauth2/code/naver
#            authorization-grant-type: authorization_code
#            scope:
#              - email
#          google:
#            client-name: google
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            redirect-uri: http://localhost:8089/login/oauth2/code/google
#            authorization-grant-type: authorization_code
#            scope:
#              - email
#          kakao:
#            client-name: kakao
#            client-id: ${KAKAO_CLIENT_ID}
#            client-secret: ""
#            redirect-uri: http://localhost:8089/login/oauth2/code/kakao
#            authorization-grant-type: authorization_code
#            scope:
#              - account_email
#
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#      login:
#        success-url: http://localhost:3000/
#        addition-info-url: http://localhost:3000/
#
##mybatis:
##  mapper-locations: classpath:mapper/**/*.xml
##  type-aliases-package: com.kyj.*
##  configuration:
##    map-underscore-to-camel-case: true
#
#
#
#
#
#
#
